cart/urls.py
from django.urls import path
from .views import (
    cart_add,
    cart_remove,
    cart_detail,
)

app_name='cart'

urlpatterns=[
    path('',cart_detail,name='cart_detail'),
    path('add/<int:product_id>/',cart_add,name='cart_add'),
    path('delete/<int:product_id>/',cart_remove,name='cart_delete'),
]

confing/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('account/',include('django.contrib.auth.urls')),
    path('admin/', admin.site.urls),
    path('account/',include('account.urls')),
    path('',include('product.urls')),
    path('cart/',include('cart.urls')),
    path('order/',include('order.urls')),
    path('coupons/', include('coupon.urls')),

]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

coupon/urls.py
from django.urls import path
from .views import coupon_apply

app_name='coupon'
urlpatterns=[
    path('apply/',coupon_apply,name="coupon_apply")
]

order/urls.py
from django.urls import path
from .views import order_create,show_session

app_name='orders'
urlpatterns=[
    path('create/',order_create,name="order_create"),
    path('show_session/',show_session,name="show_session"),

    
]

product/urls.py
from django.urls import path
from .views import (
    ListProduct,
    SearchResult,
    ProductDetail,
    CategoryList,
    )

app_name='product'

urlpatterns=[
    path('',ListProduct.as_view(),name='home'), 
    path('search_result/',SearchResult.as_view(),name='search_result'),
    path('item/<slug:slug>/',ProductDetail.as_view(),name='product_detail'),
    path('products/category/<slug:slug>/',CategoryList.as_view(),name='category_list'),

]

cart/models.py
from django.db import models

# Create your models here.

cart/forms.py
from django import forms
from django.forms.widgets import HiddenInput
from django.utils.regex_helper import Choice


PRODUCT_QUANTITY_CHOICES = [(i, str(i)) for i in range(1, 11)]

class CartAddProductFrom(forms.Form):
    color=forms.CharField(max_length=50,required=False)
    quantity=forms.TypedChoiceField(choices=PRODUCT_QUANTITY_CHOICES,coerce=int,label="تعداد محصول")
    override = forms.BooleanField(required=False,initial=False,widget=forms.HiddenInput)




    

cart/views.py
from django.shortcuts import render,HttpResponse
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_POST
from product.models import Product
from .cart import Cart
from .forms import CartAddProductFrom
from coupon.forms import CouponApplyForm
# Create your views here.


def cart_add(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)  
    if request.method=="POST":
        form = CartAddProductFrom(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            cart.add(product=product,
            quantity=cd['quantity'],
            override_quantity=cd['override'],
            color=cd['color'],
            )
        return redirect('cart:cart_detail')

    else:
        form = CartAddProductFrom()
        return HttpResponse("form is not valid ")

@require_POST
def cart_remove(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    cart.remove(product)
    return redirect('cart:cart_detail')

def cart_detail(request):
    cart = Cart(request)
    for item in cart:
        item['update_quantity_form'] = CartAddProductFrom(initial={'color':item['color'],'quantity': item['quantity'],'override': True})
    coupon_apply_form = CouponApplyForm()
    return render(request, 'cart/cart_detail.html', {'cart': cart,'coupon_apply_form': coupon_apply_form})

templates/cart/cart_detail.html
{% extends 'base.html'%}
{% load crispy_forms_tags %}
{% load widget_tweaks %}
{% block title%}سبد خرید{% endblock %}
{% block content %}
<div class="container padding-bottom-3x mb-1">
    <!-- Shopping Cart-->
    <div class="table-responsive shopping-cart" style="margin-top: 50px;margin-bottom:30px;">
        <table class="table" style="margin-top: 30px;text-align:right;direction:rtl;">
            <thead>
                <tr>
                    <th>نام محصول</th>
                    <th class="text-center">تعداد</th>
                    <th class="text-center">رنگ </th>
                    <th class="text-center">قیمت </th>
                    <th class="text-center">قیمت کل</th>
                    <th class="text-center">حذف  </th>
                </tr>
            </thead>
            <tbody>
                {% for item in cart %}
                    {% with product=item.product %}
                        <tr>
                            <td>
                                <div class="product-item">
                                    <a class="product-thumb" href="{% url 'product:product_detail' product.slug %}"><img src="{{product.thumbnail.url}}" alt="Product"></a>
                                    <div class="product-info" style="margin-bottom : 5px;">
                                        <h4 class="product-title">{{ product.title }}</a></h4>
                                    </div>
                                </div>
                            </td>
                            <td class="text-center">
                                <div class="count-input">
                                <form action="{% url "cart:cart_add" product.id %}" method="POST">
                                    {% csrf_token%}
                                    {{ item.update_quantity_form.quantity|add_class:'form-control' }}
                                    {{ item.update_quantity_form.override }}
                                    <input type="text" name="color" value="{{item.color}}" hidden required="" id="id_color">

                                    <br>
                                    <input type="submit" class="btn btn-primary" value="اپدیت">
                                </form>
                                </div>
                            </td>
                            {% if item.color %}
                                <td class="text-center text-lg text-medium">{{item.color}}</td>
                            {% else %}
                                <td class="text-center text-lg text-medium">موجود نیست</td>
                            {% endif %}
                            <td class="text-center text-lg text-medium">{{item.price}}</td>
                            <td class="text-center text-lg text-medium">{{item.total_price}}</td>

                            <td class="text-center">
                                <form action="{% url 'cart:cart_delete' product.id %}" method="POST" >
                                    {% csrf_token %}
                                    <button type="submit" class="btn btn-danger">حذف</button>
                                </form>
                            </tr>
                    {% endwith %}
                {% endfor %}
            </tbody>
        </table>
    </div>
    <div class="shopping-cart-footer">
            {% with total_items=cart|length %}
                {% if total_items > 0 %}
                    {% if cart.coupon %}
                        <div class="column text-lg">قیمت کل محصولات(با تخفیف): <span class="text-medium">{{ cart.get_total_price_after_discount }}تومان</span></div>                    
                    {% endif %}
                    <div class="column text-lg">قیمت کل محصولات: <span class="text-medium">{{ cart.get_total_price }}تومان</span></div>                    
                    <div class="column text-lg">تعداد محصول شما:<span class="text-medium">{{ total_items }}</span></div>     
                {% else %}
                <div class="column text-lg"><span class="text-medium"> شما هیچ محصولی ندارید</span></div>     
                {% endif %} 
            {% endwith %}
    </div>
    {% if cart %}
    <div class="shopping-cart-footer">
        <div class="column">
            <form class="coupon-form" method="POST" action="{% url 'coupon:coupon_apply' %}">
                {% csrf_token %}
                <div class="form-group">
                    <div class="input-group"> {{coupon_apply_form.code|add_class:'form-control'}} <span class="input-group-append"> <button type="submit" class="btn btn-primary btn-apply coupon">وارد</button> </span> </div>
                </div>
            </form>
        </div>
        <div class="column">

            {% if request.user.is_authenticated and request.user.is_not_empty_field %}
            <div class="column"><a class="btn btn-success" href="{% url 'orders:order_create'%}">ادامه فرایند خرید</a></div>
            {% elif not request.user.is_authenticated %}
            <div class="column"><a class="btn btn-success" href="{% url 'login'%}?next={{request.path}}">ورود به حساب کاربری</a></div>
            {% else %}
            <div class="column"><a class="btn btn-success" href="{% url 'account:address_update'%}">ادامه فرایند خرید</a></div>
            {% endif %}
        {% endif %}
        </div>
    </div>
    
</div>

{% endblock %}