cart/urls.py
from django.urls import path
from .views import (
    cart_add,
    cart_remove,
    cart_detail,
)

app_name='cart'

urlpatterns=[
    path('',cart_detail,name='cart_detail'),
    path('add/<int:product_id>/',cart_add,name='cart_add'),
    path('delete/<int:product_id>/',cart_remove,name='cart_delete'),
]

confing/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('account/',include('django.contrib.auth.urls')),
    path('admin/', admin.site.urls),
    path('account/',include('account.urls')),
    path('',include('product.urls')),
    path('cart/',include('cart.urls')),
    path('order/',include('order.urls')),
    path('coupons/', include('coupon.urls')),

]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

product/urls.py
from django.urls import path
from .views import (
    ListProduct,
    SearchResult,
    ProductDetail,
    CategoryList,
    )

app_name='product'

urlpatterns=[
    path('',ListProduct.as_view(),name='home'), 
    path('search_result/',SearchResult.as_view(),name='search_result'),
    path('item/<slug:slug>/',ProductDetail.as_view(),name='product_detail'),
    path('products/category/<slug:slug>/',CategoryList.as_view(),name='category_list'),

]

cart/models.py
from django.db import models

# Create your models here.

product/models.py
from django.db import models
from django.db.models.deletion import SET_NULL
from django.db.models.expressions import Col
from account.models import User
from django.urls import reverse
from django.db.models import Q
from django.utils.html import format_html
from django.db.models import Count
# Create your models here.


class ProductManager(models.Manager):
    def product_publish(self):
        return self.filter(status='p')

    def number_of_visits(self):
        return self.annotate(count=Count('visits'))
    

class CategoryManager(models.Manager):
    def category_publish(self):
        return self.filter(status='p')

class Category(models.Model):
    STATUS_CHOICE={
        ('p','انتشار'),
        ('d','پیش نویس'),
    }
    parent=models.ForeignKey('self',on_delete=models.SET_NULL,null=True,blank=True,default=None,related_name='children',verbose_name="والد")
    title=models.CharField(max_length=200,verbose_name='عنوان')
    slug=models.SlugField(max_length=100,unique=True,verbose_name='ادرس دسته بندی')
    position=models.IntegerField(verbose_name='پوزیشن')
    status=models.CharField(max_length=1,choices=STATUS_CHOICE,verbose_name='وضعیت')
 
    def get_absolute_url(self):
        return reverse('product:category_list',args=[self.slug])

    def __str__(self):
        return self.title

    class Meta:
        verbose_name='دسته بندی'
        verbose_name_plural='دسته بندی ها'
        ordering=["position"]
    objects=CategoryManager()

class Color(models.Model):
    code=models.CharField(max_length=50,verbose_name='کد رنگ')
    name=models.CharField(max_length=50,verbose_name='نام رنگ')
    
    def __str__(self):
        return self.name
    def color_pic(self):
        return format_html(f'<p style="background-color:{self.code};width:200px;">{self.name}</p>')
    class Meta:
        verbose_name='رنگ'
        verbose_name_plural='رنگ ها'
    color_pic.short_description = 'رنگ'



class IpAddress(models.Model):
    ip=models.GenericIPAddressField()

    def __str__(self):
        return str(self.ip)


class Product(models.Model):
    STATUS_CHOICE={
        ('p','انتشار'),
        ('d','پیش نویس'),
    }
    user=models.ForeignKey(User,on_delete=models.CASCADE,verbose_name='مدیر')
    title=models.CharField(max_length=100,verbose_name='عنوان')
    slug=models.SlugField(max_length=100,unique=True,verbose_name='ادرس محصول')
    category=models.ManyToManyField(Category,verbose_name='دسته ها',related_name='product')
    color=models.ManyToManyField(Color,verbose_name='رنگ',blank=True)
    spec=models.TextField(verbose_name='اطلاعات راجب محصول')
    description=models.TextField(verbose_name='توضیح درباره محصول', blank=True,null=True)
    price=models.FloatField(verbose_name='قیمت کالا')
    thumbnail=models.ImageField(upload_to='image',verbose_name='عکس',blank=False,null=False)
    created=models.DateTimeField(auto_now_add=True,verbose_name='زمان ساخت')
    updated=models.DateField(auto_now=True,verbose_name='زمان تغییر')
    status=models.CharField(max_length=1,choices=STATUS_CHOICE,verbose_name='وضعیت')
    exist=models.BooleanField(default=True,verbose_name='موجود بودن محصول') 
    visits=models.ManyToManyField(IpAddress,related_name='product',verbose_name='تعداد بازدید ها',blank=True)

    def __str__(self):
        return self.title
        
    def get_absolute_url(self):
        return reverse('product:product_detail',
                        args=[self.slug])

    class Meta:
        verbose_name='محصول'
        verbose_name_plural='محصولات'
        ordering=['-created']
    objects=ProductManager()


class ImageProduct(models.Model):
    product=models.ForeignKey(Product,on_delete=models.CASCADE,verbose_name='محصول',related_name='product_image')
    image=models.FileField(upload_to='image',verbose_name='عکس')

    class Meta:
        verbose_name='عکس'
        verbose_name_plural='عکس ها'

cart/forms.py
from django import forms
from django.forms.widgets import HiddenInput
from django.utils.regex_helper import Choice


PRODUCT_QUANTITY_CHOICES = [(i, str(i)) for i in range(1, 11)]

class CartAddProductFrom(forms.Form):
    color=forms.CharField(max_length=50,required=False)
    quantity=forms.TypedChoiceField(choices=PRODUCT_QUANTITY_CHOICES,coerce=int,label="تعداد محصول")
    override = forms.BooleanField(required=False,initial=False,widget=forms.HiddenInput)




    

cart/views.py
from django.shortcuts import render,HttpResponse
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_POST
from product.models import Product
from .cart import Cart
from .forms import CartAddProductFrom
from coupon.forms import CouponApplyForm
# Create your views here.


def cart_add(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)  
    if request.method=="POST":
        form = CartAddProductFrom(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            cart.add(product=product,
            quantity=cd['quantity'],
            override_quantity=cd['override'],
            color=cd['color'],
            )
        return redirect('cart:cart_detail')

    else:
        form = CartAddProductFrom()
        return HttpResponse("form is not valid ")

@require_POST
def cart_remove(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    cart.remove(product)
    return redirect('cart:cart_detail')

def cart_detail(request):
    cart = Cart(request)
    for item in cart:
        item['update_quantity_form'] = CartAddProductFrom(initial={'color':item['color'],'quantity': item['quantity'],'override': True})
    coupon_apply_form = CouponApplyForm()
    return render(request, 'cart/cart_detail.html', {'cart': cart,'coupon_apply_form': coupon_apply_form})

product/views.py
from django.shortcuts import get_object_or_404, render,HttpResponse
from product.models import Product,Category
from django.views.generic import ListView,DetailView
from django.db.models import Q
from cart.forms import CartAddProductFrom
from django.contrib.sites.shortcuts import get_current_site

# Create your views here.

class ListProduct(ListView):
    queryset=Product.objects.product_publish()[:4]
    template_name='products/home.html'
    context_object_name='products'

    def get_context_data(self,**kwargs):
        context=super().get_context_data(**kwargs)
        context['most_visit_product']=Product.objects.number_of_visits().order_by('-count')[:4]
        site=get_current_site(self.request)
        print(site.domain)
        return context
         
class ProductDetail(DetailView):
    template_name='products/detail.html' 
    context_object_name='product'

    def get_object(self):
        global product
        global slug
        slug=self.kwargs.get('slug')
        product=get_object_or_404(Product.objects.product_publish(),slug=slug)
        ip_address=self.request.user.ip_address

        if not ip_address in product.visits.all():
            product.visits.add(ip_address)

        return product

    def get_context_data(self,**kwargs):
        context=super().get_context_data(**kwargs)
        related_product=Product.objects.filter(title__icontains=product.title[:5],).exclude(slug=slug)[:5]
        context['related_products']=related_product
        context['form']=CartAddProductFrom()
        return context   

class SearchResult(ListView):
    template_name='products/search_result.html'
    context_object_name='products'
    model=Product
    paginate_by=10
    def get_queryset(self):
        query=self.request.GET.get('q',"None")
        object_list=Product.objects.filter(Q(title__icontains=query) | Q(spec__icontains=query))
        return object_list

class CategoryList(ListView):
    template_name='products/category_list.html'
    context_object_name='products'
    paginate_by=2
    def get_queryset(self):
        slug=self.kwargs.get('slug')
        category=get_object_or_404(Category.objects.category_publish(),slug=slug)
        return category.product.product_publish()

templates/products/cart.html
<html>
    <head>
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
        <link rel="stylesheet" href="https://pro.fontawesome.com/releases/v5.10.0/css/all.css" integrity="sha384-AYmEC3Yw5cVb3ZcuHtOA93w35dYTsvhLPVnYs9eStHfGJvOvKxVfELGroGkvsg+p" crossorigin="anonymous"/>
<style>

</style>
    </head>
    <body>
        <form action="">

              <li>
                <label>
                  <input type="radio" name="color" value="blue">
                  <span class="swatch" style="background-color:#6e8cd5"></span> Blue
                </label>
              </li>
              <li>
                <label>
                  <input type="radio" name="color" value="green">
                  <span class="swatch" style="background-color:#44c28d"></span> Green
                </label>
              </li>
            </ul> 
          </div> 
        </form>
    </body>
</html>

templates/products/category_list.html
{% extends "products/list.html"%}
{%block title%}لیست کالاها{% endblock %}

{% block previous_page_url %}?page={{ page_object.previous_page_number }}{% endblock %}
{% block number_page_url %}?page={{ i }}{% endblock %}
{% block next_page_url %}?page={{ page_obj.next_page_number }}{% endblock %}

templates/products/detail.html
{% extends "base.html"%}
{% load widget_tweaks %}
<title>{%block title%}{% endblock %}</title>


{% block content %}
<div class="container mt-5 mb-5" style="text-align: right;direction:rtl">
    <div class="card">
        <div class="row g-0">
            <div class="col-md-6 border-end">
                <div class="d-flex flex-column justify-content-center">
                    <div class="main_image"> <img src="{{product.thumbnail.url}}" id="main_product_image" width="350"> </div>
                    {% if product.product_image %}
                    <div class="thumbnail_images">
                        <ul id="thumbnail">
                            <li><img onclick="changeImage(this)" src="{{product.thumbnail.url}}" width="70"></li>
                            {% for image in product.product_image.all %}
                            <li><img onclick="changeImage(this)" src="{{image.image.url}}" width="70"></li>
                            {% endfor %}
                        </ul>
                    </div>
                    {% endif %}
                </div>
            </div>
            <div class="col-md-6">
                <div class="p-3 right-side">
                    <div class="ratings d-flex flex-row align-items-center">
                        <div class="d-flex flex-row"> <i class='bx bxs-star'></i> <i class='bx bxs-star'></i> <i class='bx bxs-star'></i> <i class='bx bxs-star'></i> <i class='bx bx-star'></i> </div> <span> بازدید {{product.visits.count}}</span>
                    </div>
                    <div class="d-flex justify-content-between align-items-center">
                        <h3>{{product.title}}</h3>
                    </div>
                    <div class="mt-2 pr-3 content">
                        <details>
                            <summary>ویژگی های کالا</summary>
                            {{product.spec|linebreaks}}
                        </details>
                    </div>
                    <h3>{{product.price}}تومان</h3>
                    <form action="{% url 'cart:cart_add' product.id %}" method="POST">
                        {% csrf_token %}
                            {% if product.color.exists %}
                            <span>رنگ محصول:</span>
                            <div class="colors">
                                <ul>
                                    {% for color in product.color.all %}
                                    <li>
                                        <label>
                                          <input id='id_color' type="radio" name="color" value="{{color.name}}">
                                          <span class="swatch" style="background-color:{{color.code}}"></span>
                                        </label>
                                    </li>
                                    {% endfor %}
                                </ul> 
                              </div> 
                            {% endif %}
                        <div class="mt-5">
                                <label for="id_quantity">تعداد محصول:</label>
                                {{ form.quantity |add_class:"form-select"}}
                                {{ form.override }}
                        </div>
                        <div class="buttons d-flex flex-row mt-5 gap-3"><button class="btn-lg btn-dark">اضافه به سبد خرید</button> </div>
                    </form>
                    </div>
                </div>
            </div>
            <div class="col-11 border-top p-3">
                <p>مشخصات محصول</p>
                <p>{{product.description|escape|linebreaks}}</p>
            </div>
        </div>
    </div>


    <div class="container-fluid mt-5 mb-5" style="text-align: right;direction:rtl;">
        {% if product.status == "p" or product.status == "f" %}
            <div class="row g-2 p-5 ">
                {% for product in related_products%}
                    <div class="col-md-3 ">
                        <div class="product py-4">
                            <div class="text-center"> <img src="{{product.thumbnail.url}}" width="200"> </div>
                            <div class="about text-center">
                                <a href="{{product.get_absolute_url}}"><p>{{product.title}}</h5></a> <p>{{product.price}}تومان</span>
                            </div>
                        </div>
                    </div>
                {% endfor %}
        {% endif %}
    </div>

        </div>
    </div>  
</div>
{% endblock %}

templates/products/home.html
{% extends "base.html"%}
{%block title%}خانه{% endblock %}
{% block content %}
<div class="container mt-5 mb-5" style="text-align: right;direction:rtl;">
  <div class="row g-2"> 
    <p>جدید ترین محصولات</p>
    {% for product in products%}
          <div class="col-md-5">
            <div class="product py-4">
                <div class="text-center"> <img src="{{product.thumbnail.url}}" width="200"> </div>
                <div class="about text-center">
                    <a href="{{product.get_absolute_url}}"><p>{{product.title}}</h5></a> <p>{{product.price}}تومان</p>
                    {% if product.exist %}
                      <p class="text-success">محصول موجود است </p>
                    {% else %}
                      <p class="text-danger">درحال حاضر محصول موجود نیست</p>
                    {% endif %}
                </div>
            </div>
        </div>
    {% endfor %}
    <p>پربازدیدترین محصولات</p>
    {% for product in most_visit_product %}
    <div class="col-md-5">
      <div class="product py-4">
          <div class="text-center"> <img src="{{product.thumbnail.url}}" width="200"> </div>
          <div class="about text-center">
              <a href="{{product.get_absolute_url}}"><p>{{product.title}}</h5></a> <p>{{product.price}}تومان</p>
              {% if product.exist %}
                <p class="text-success">محصول موجود است </p>
              {% else %}
                <p class="text-danger">درحال حاضر محصول موجود نیست</p>
            {% endif %}
          </div>
      </div>
  </div>
{% endfor %}
  </div>
</div>
{% endblock %}

templates/products/list.html
{% extends "base.html"%}
{%block title%}{% endblock %}
{% block content %}
<div class="container mt-5 mb-5" style="text-align: right;direction:rtl;">
      <div class="row g-2">
        {% for product in products%}
        <div class="col-md-5">
          <div class="product py-4">
              <div class="text-center"> <img src="{{product.thumbnail.url}}" width="200"> </div>
              <div class="about text-center">
                  <a href="{{product.get_absolute_url}}"><p>{{product.title}}</h5></a> <p>{{product.price}}تومان</span>
              </div>
          </div>
      </div>
        {% empty %}
          <div class="text-center">
            <h2 style="color: rgb(172, 69, 69);padding-top:60px;margin-right:370px;padding-bottom:60px;">نتیجه ای یافت نشد</h2>
          </div>
      {% endfor %}
      </div>
</div>
</div>
<!-- paginator !-->
{% if page_obj.has_other_pages %}
<div class="center">
  <div class="pagination">
    {% if page_obj.has_previous %}
      <a href="{% block previous_page_url %}{% endblock %}">&laquo;</a>
    {% else %}
      <a class="disable">&laquo;</a>
    {% endif %}
    {% for i in paginator.page_range %}
      {% if page_obj.number == i %}
        <a class='active'>{{ i }}</a>     
      {% else %}
        <a href="{% block number_page_url %}{% endblock %}">{{ i }}</a>
      {% endif%}
    {% endfor %}
    {% if page_obj.has_next %}
        <a href="{% block next_page_url %}{% endblock %}">&raquo;</a>
    {% else %}
      <a class="disable">&raquo;</a>
    {% endif %}
  </div>
</div>
{% endif %}

{% endblock %}

templates/products/search_result.html
{% extends "products/list.html"%}
{%block title%}نتیجه{% endblock %}
{% block previous_page_url %}?page={{ page_object.previous_page_number }}{% if request.GET.q %}&q={{ request.GET.q }}{% endif %}{% endblock %}
{% block number_page_url %}?page={{ i }}{% if request.GET.q %}&q={{ request.GET.q }}{% endif %}{% endblock %}
{% block next_page_url %}?page={{ page_obj.next_page_number }}{% if request.GET.q %}&q={{ request.GET.q }}{% endif %}{% endblock %}