cart/urls.py
from django.urls import path
from .views import (
    cart_add,
    cart_remove,
    cart_detail,
)

app_name='cart'

urlpatterns=[
    path('',cart_detail,name='cart_detail'),
    path('add/<int:product_id>/',cart_add,name='cart_add'),
    path('delete/<int:product_id>/',cart_remove,name='cart_delete'),
]

confing/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('account/',include('django.contrib.auth.urls')),
    path('admin/', admin.site.urls),
    path('account/',include('account.urls')),
    path('',include('product.urls')),
    path('cart/',include('cart.urls')),
    path('order/',include('order.urls')),
    path('coupons/', include('coupon.urls')),

]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

product/urls.py
from django.urls import path
from .views import (
    ListProduct,
    SearchResult,
    ProductDetail,
    CategoryList,
    )

app_name='product'

urlpatterns=[
    path('',ListProduct.as_view(),name='home'), 
    path('search_result/',SearchResult.as_view(),name='search_result'),
    path('item/<slug:slug>/',ProductDetail.as_view(),name='product_detail'),
    path('products/category/<slug:slug>/',CategoryList.as_view(),name='category_list'),

]

product/models.py
from django.db import models
from django.db.models.deletion import SET_NULL
from django.db.models.expressions import Col
from account.models import User
from django.urls import reverse
from django.db.models import Q
from django.utils.html import format_html
from django.db.models import Count
# Create your models here.


class ProductManager(models.Manager):
    def product_publish(self):
        return self.filter(status='p')

    def number_of_visits(self):
        return self.annotate(count=Count('visits'))
    

class CategoryManager(models.Manager):
    def category_publish(self):
        return self.filter(status='p')

class Category(models.Model):
    STATUS_CHOICE={
        ('p','انتشار'),
        ('d','پیش نویس'),
    }
    parent=models.ForeignKey('self',on_delete=models.SET_NULL,null=True,blank=True,default=None,related_name='children',verbose_name="والد")
    title=models.CharField(max_length=200,verbose_name='عنوان')
    slug=models.SlugField(max_length=100,unique=True,verbose_name='ادرس دسته بندی')
    position=models.IntegerField(verbose_name='پوزیشن')
    status=models.CharField(max_length=1,choices=STATUS_CHOICE,verbose_name='وضعیت')
 
    def get_absolute_url(self):
        return reverse('product:category_list',args=[self.slug])

    def __str__(self):
        return self.title

    class Meta:
        verbose_name='دسته بندی'
        verbose_name_plural='دسته بندی ها'
        ordering=["position"]
    objects=CategoryManager()

class Color(models.Model):
    code=models.CharField(max_length=50,verbose_name='کد رنگ')
    name=models.CharField(max_length=50,verbose_name='نام رنگ')
    
    def __str__(self):
        return self.name
    def color_pic(self):
        return format_html(f'<p style="background-color:{self.code};width:200px;">{self.name}</p>')
    class Meta:
        verbose_name='رنگ'
        verbose_name_plural='رنگ ها'
    color_pic.short_description = 'رنگ'



class IpAddress(models.Model):
    ip=models.GenericIPAddressField()

    def __str__(self):
        return str(self.ip)


class Product(models.Model):
    STATUS_CHOICE={
        ('p','انتشار'),
        ('d','پیش نویس'),
    }
    user=models.ForeignKey(User,on_delete=models.CASCADE,verbose_name='مدیر')
    title=models.CharField(max_length=100,verbose_name='عنوان')
    slug=models.SlugField(max_length=100,unique=True,verbose_name='ادرس محصول')
    category=models.ManyToManyField(Category,verbose_name='دسته ها',related_name='product')
    color=models.ManyToManyField(Color,verbose_name='رنگ',blank=True)
    spec=models.TextField(verbose_name='اطلاعات راجب محصول')
    description=models.TextField(verbose_name='توضیح درباره محصول', blank=True,null=True)
    price=models.FloatField(verbose_name='قیمت کالا')
    thumbnail=models.ImageField(upload_to='image',verbose_name='عکس',blank=False,null=False)
    created=models.DateTimeField(auto_now_add=True,verbose_name='زمان ساخت')
    updated=models.DateField(auto_now=True,verbose_name='زمان تغییر')
    status=models.CharField(max_length=1,choices=STATUS_CHOICE,verbose_name='وضعیت')
    exist=models.BooleanField(default=True,verbose_name='موجود بودن محصول') 
    visits=models.ManyToManyField(IpAddress,related_name='product',verbose_name='تعداد بازدید ها',blank=True)

    def __str__(self):
        return self.title
        
    def get_absolute_url(self):
        return reverse('product:product_detail',
                        args=[self.slug])

    class Meta:
        verbose_name='محصول'
        verbose_name_plural='محصولات'
        ordering=['-created']
    objects=ProductManager()


class ImageProduct(models.Model):
    product=models.ForeignKey(Product,on_delete=models.CASCADE,verbose_name='محصول',related_name='product_image')
    image=models.FileField(upload_to='image',verbose_name='عکس')

    class Meta:
        verbose_name='عکس'
        verbose_name_plural='عکس ها'

product/views.py
from django.shortcuts import get_object_or_404, render,HttpResponse
from product.models import Product,Category
from django.views.generic import ListView,DetailView
from django.db.models import Q
from cart.forms import CartAddProductFrom
from django.contrib.sites.shortcuts import get_current_site

# Create your views here.

class ListProduct(ListView):
    queryset=Product.objects.product_publish()[:4]
    template_name='products/home.html'
    context_object_name='products'

    def get_context_data(self,**kwargs):
        context=super().get_context_data(**kwargs)
        context['most_visit_product']=Product.objects.number_of_visits().order_by('-count')[:4]
        site=get_current_site(self.request)
        print(site.domain)
        return context
         
class ProductDetail(DetailView):
    template_name='products/detail.html' 
    context_object_name='product'

    def get_object(self):
        global product
        global slug
        slug=self.kwargs.get('slug')
        product=get_object_or_404(Product.objects.product_publish(),slug=slug)
        ip_address=self.request.user.ip_address

        if not ip_address in product.visits.all():
            product.visits.add(ip_address)

        return product

    def get_context_data(self,**kwargs):
        context=super().get_context_data(**kwargs)
        related_product=Product.objects.filter(title__icontains=product.title[:5],).exclude(slug=slug)[:5]
        context['related_products']=related_product
        context['form']=CartAddProductFrom()
        return context   

class SearchResult(ListView):
    template_name='products/search_result.html'
    context_object_name='products'
    model=Product
    paginate_by=10
    def get_queryset(self):
        query=self.request.GET.get('q',"None")
        object_list=Product.objects.filter(Q(title__icontains=query) | Q(spec__icontains=query))
        return object_list

class CategoryList(ListView):
    template_name='products/category_list.html'
    context_object_name='products'
    paginate_by=2
    def get_queryset(self):
        slug=self.kwargs.get('slug')
        category=get_object_or_404(Category.objects.category_publish(),slug=slug)
        return category.product.product_publish()

templates/products/partials/navbar.html
<header>
    <nav class="navbar navbar-expand-md navbar-light bg-dark border-bottom">
        <div class="container-fluid">

            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse"
                aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse" id="navbarCollapse">
                
                <ul class="navbar-nav me-auto mb-2 mb-md-0">
                    <a href="{% url 'cart:cart_detail'%}"><i class="nav-item fas fa-shopping-cart fa-2x text-white"></i></a>           


                    <div class="dropdown">

                        <a class="fas fa-user fa-2x dropdown-toggle text-white" href="#" role="button" style="text-decoration: none;margin: 0 20px 0 20px;" id="dropdownMenuLink" data-bs-toggle="dropdown" aria-expanded="false">
                        </a>
                        <ul class="dropdown-menu" aria-labelledby="dropdownMenuLink">
                        {% if request.user.is_authenticated %}
                          <li><a class="dropdown-item" href="{% url 'account:profile' %}">پروفایل</a></li>
                          <li><a class="dropdown-item" href="{% url 'logout' %}?next={{request.path}}">خروج</a></li>
                        {% else %}
                          <li><a class="dropdown-item" href="{% url 'login' %}?next={{request.path}}">ورود</a></li>
                        {% endif %}
                        </ul>
                      </div>

                    <form action="{% url 'product:search_result'%}" class="d-flex">
                        <input class="form-control me-2" type="search" placeholder="جستجو" aria-label="Search" name='q'>
                        <button class="btn btn-outline-success" type="submit">جستجو</button>
                    </form>    
                </ul>

                <li class="nav-item dropdown navbar-nav me-right-auto mb-2 mb-md-0" id="myDropdown" style="text-align: right;direction:rtl;">
                    <a class="nav-link dropdown-toggle text-white" href="#" data-bs-toggle="dropdown"> دسته بندی </a>
                    <ul class="dropdown-menu">
                        {% for item in categorys  %}
                            {% if item.parent == None%}
                                <li>
                                    <a class="dropdown-item" href="{% url 'product:category_list' item.slug  %}"> 
                                        {{item.title}}
                                    </a>
                                    {% if item.children.all %}
                                        {% include 'products/partials/navbar_nested.html'%}
                                    {% endif %}
                                </li>
                            {% endif %}
                        {% endfor %}
                    </ul>
                </li>
               <a href="{% url 'product:home'%}"><i class="fa-home fa text-white" aria-hidden="true" style="padding-right:10px; padding-left:18px;"></i></a>
            </div>
        </div>
    </nav>
</header>

templates/products/partials/navbar_nested.html
<ul class="submenu dropdown-menu">
    {% for item in item.children.all %}
        <li>
            <a class="dropdown-item" href="{% url 'product:category_list' item.slug  %}">
                {{item.title}}
            </a>
            {% if item.children.all %}
                {% include 'products/partials/navbar_nested.html' %}
            {% endif %}    
        </li>
    {% endfor %}
</ul>